app.py
from flask import Flask

from tools.database import Database

app = Flask(__name__)


def register_bps():
    from blueprints.admin import admin
    app.register_blueprint(admin)
    from blueprints.view import view
    app.register_blueprint(view)
    from blueprints.user import user
    app.register_blueprint(user)
    from blueprints.category import cat
    app.register_blueprint(cat)
    from blueprints.link import link
    app.register_blueprint(link)


def init():
    Database().init(app.config['DB_CONFIG'])
    register_bps()


if __name__ == '__main__':
    app.config.from_object('tools.config.DevelopmentConfig')
    init()
    app.run(host='0.0.0.0')

blueprints/admin.py
from flask import Blueprint, render_template, request, session, url_for, redirect

from tools.database import db

admin = Blueprint('admin', __name__)


@admin.route('/login', methods=['POST'])
def login():
    username = request.form['username']
    password = request.form['password']
    curr_user = db.find_all("SELECT * FROM user WHERE username=%s AND password =%s ORDER BY id DESC", username,
                            password)
    if curr_user is not None:
        session['is_login'] = True
        session['user'] = curr_user
        return redirect(url_for('user.show_users'))
    else:
        error = 'Invalid username or password!'
    return render_template('login.html', error=error)


@admin.route('/login', methods=['GET'])
def show_login():
    return render_template('login.html')


@admin.route('/logout', methods=['GET'])
def logout():
    return 'logout'

blueprints/category.py
from flask import Blueprint

cat = Blueprint("cat", __name__)

blueprints/link.py
from flask import Blueprint, render_template

link = Blueprint('link', __name__, url_prefix='/links')


@link.route('/show', methods=['GET'])
def show_links():

    return render_template('links/show_users.html')

blueprints/user.py
from flask import Blueprint, render_template

from tools.database import db

user = Blueprint("user", __name__, url_prefix='/user')


@user.route('/show', methods=['GET'])
def show_users():
    users = db.find_all("select * from user order by id desc")
    print users
    return render_template('user/show_users.html', users=users)

blueprints/view.py
from flask import Blueprint

view = Blueprint("view", __name__)


@view.route('/', methods=['GET'])
def index():
    return 'Hi Betty!!'

templates/admin_header.html
<!doctype html>
<title>Betty Admin</title>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='admin.css') }}">
<div class="page">
    <h1>Betty</h1>
    <div class="metanav">
        {% if not session.logged_in %}
            <a href="{{ url_for('admin.login') }}">log in</a>
        {% else %}
            <a href="{{ url_for('admin.logout') }}">log out</a>
        {% endif %}
    </div>
    {% for message in get_flashed_messages() %}
        <div class="flash">{{ message }}</div>
    {% endfor %}
    {% block body %}{% endblock %}
</div>

templates/layout/admin_header.html
<!doctype html>
<title>Betty Admin</title>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='admin.css') }}">
<div class="page">
    <h1>Betty</h1>
    <div class="metanav">
        {% if not session.is_login %}
            <a href="{{ url_for('admin.login') }}">log in</a>
        {% else %}
            <a href="{{ url_for('admin.logout') }}">log out</a>
        {% endif %}
    </div>
    {% for message in get_flashed_messages() %}
        <div class="flash">{{ message }}</div>
    {% endfor %}
    {% block body %}{% endblock %}
</div>

templates/links/show_links.html
{% extends "admin_header.html" %}
{% block body %}
<ul class="entries">
    {% for entry in entries %}
    <li><h2>{{ entry.title }}</h2>{{ entry.text|safe }}</li>
    {% else %}
    <li><em>Unbelievable. No entries here so far</em></li>
    {% endfor %}
</ul>
{% endblock %}

templates/login.html
{% extends "layout/admin_header.html" %}
{% block body %}
    <h2>Login</h2>
    {% if error %}<p class="error"><strong>Error:</strong> {{ error }}{% endif %}
    <form action="{{ url_for('admin.login') }}" method="post">
        <dl>
            <dt>用户名：<input type="text" name="username"></dt>
            <dt>密　码：<input type="password" name="password"></dt>
            <dt>
                <input type="submit" value="登录">
                <input type="reset" value="重置">
            </dt>
        </dl>
    </form>
{% endblock %}

templates/user/show_users.html
{% extends "layout/admin_header.html" %}
{% block body %}
<ul class="entries">
    {% for u in users %}
    <li><h2>{{ u.username }}</h2>{{ u.display_name|safe }}</li>
    {% else %}
    <li><em>Unbelievable. No entries here so far</em></li>
    {% endfor %}
</ul>
{% endblock %}